# ========================
# Build Settings
# ========================
[build]
  publish = "dist"        # Your React build output folder
  command = "npm run build"

# ========================
# Redirect Rules
# ========================

# SPA routing: Serve index.html for all unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Example: Permanent redirect from old pages
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

# API proxy routing (if you have a backend API)
[[redirects]]
  from = "/api/*"
  to = "https://your-api-server.com/:splat"
  status = 200
  force = true

# ========================
# Header Rules
# ========================

# Global security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Optimized caching for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# Caching for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
